# server:
#   port: 9000
# server.servlet.session.tracking-modes: cookie
logging:
  level:
    org.springframework:
      security: DEBUG
      web: DEBUG
    com.example.DemoAuthenticator: DEBUG
spring:
  application.name: "DemoAuthenticator"
  # security:
  #   user:
  #     name: user
  #     password: password
